
variables:
  buildScheme: 'Azure14Ocak'  # Uygulamanızın Xcode scheme'ini buraya girin.
  buildSdk: 'iphoneos'
  buildConfiguration: 'Release'
  workspacePath: '**/*.xcodeproj'  # Eğer bir workspace kullanıyorsanız, burayı ayarlayın.
  xcodeVer: 'default'  # Seçenekler: 8, 9, 10, 11, 12, default, specifyPath

trigger:
  branches:
    include:
    - master
    - main
    - develop

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - main
      - develop
    always: true

pool:
  name: 'Default'

steps:
- checkout: self


- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository to https://dev.azure.com/erdieergene/_git/Azure14Ocak'
  inputs:
    sourceGitRepositoryPersonalAccessToken: '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'
    sourceGitRepositoryCloneDirectoryName: master
    destinationGitRepositoryUri: 'https://dev.azure.com/erdieergene/_git/Azure14Ocak'
    destinationGitRepositoryPersonalAccessToken: zix2i62qibzxfrvncrq2ogmgw6tiqwodw5htffsbwmjyge2vzz3q

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: $(buildScheme)
    sdk: $(buildSdk)
    configuration: $(buildConfiguration)
    xcWorkspacePath: $(workspacePath)
    xcodeVersion: $(xcodeVer)

- task: Xcode@5
  inputs:
    actions: 'archive'
    scheme: $(buildScheme)
    sdk: $(buildSdk)
    configuration: $(buildConfiguration)
    xcWorkspacePath: $(workspacePath)
    xcodeVersion: $(xcodeVer)
    packageApp: true
    archivePath: '$(Build.ArtifactStagingDirectory)/$(buildScheme).xcarchive'
